### PR TITLE
Resolves 'Panic on http2 timeout '

### PR DESCRIPTION
**Pull request by JohnDimas**
Fixes https://github.com/Byron/google-apis-rs/issues/347

### CODE REVIEW

**Review by Byron — CHANGES_REQUESTED** [review]
Thanks a lot for tackling this!

Could you please translate the changes in `gen/` to the `src/` directory which contains the template source files that will apply to all generated files under `gen/`. Any changes to `gen/` will be overwritten.

Running `make` will provide an overview of possible targets, and in this case it's possible to test changes in the templates by running cargo on the generated output like so `make drive3-cli-cargo ARGS=check`.

Thanks

**Comment by JohnDimas** [comment]
The only thing I did was to modify `src/rust/api/client.rs` and run `make regen-apis`. I did not modify any file in gen/ by myself :+1: 

Should I regen drive3-api by an other way ?
I did run `make drive3-cli-cargo ARGS=check` but everything seems fine

**Comment by Byron** [comment]
Thanks for the clarification and for your help - it was confusing for me to see more changed files in `gen/` than in `src/`. I resolved this by undoing the changes in `gen/` first to regenerate them myself with similar results. I didn't look into why that is either 😅.

That said, you will find [drive 3 v4.0.1 on crates.io](https://crates.io/crates/google-drive3).

**Comment by JohnDimas** [comment]
Thank you :rocket:

**Pull request merged**
