### PR TITLE
chore: add places api v1

### PR DESCRIPTION
**Pull request by b0xtch**
Add support for places api

### CODE REVIEW

**Comment by Byron** [comment]
Thanks a lot!

**Comment by b0xtch** [comment]
> Thanks a lot!

ofc qq on the publishing I am not sure what the procedure is! should I publish I don't see it in the CI either

**Comment by Byron** [comment]
No, please don't publish it.

It doesn't show in CI as CI only tests a small subset of APIs and CLIs - otherwise it would never finish.

I will re-publish the crates in the coming days (it was [also requested elsewhere](https://github.com/Byron/google-apis-rs/pull/510#issuecomment-2412977165)).

**Comment by b0xtch** [comment]
> No, please don't publish it.
> 
> It doesn't show in CI as CI only tests a small subset of APIs and CLIs - otherwise it would never finish.
> 
> I will re-publish the crates in the coming days (it was [also requested elsewhere](https://github.com/Byron/google-apis-rs/pull/510#issuecomment-2412977165)).

you got it, thanks 🙏

**Pull request merged**
