### PR TITLE
Map 'any' JSON Schema type to json::Value instead of String

### LINKED ISSUE #403: 'any' JSON Schema type should be mapped to a json::Value instead of a String
Related to #336

Currently there is a `TODO`  stating:
```
# TODO: Figure out how to handle it. It's 'interface' in Go ...
````
(https://github.com/Byron/google-apis-rs/blob/main/src/generator/lib/types.py#L33)

I think the only suitable type here is `json::Value`.    
Using `String`  makes it it impossible to build some payloads, as mentioned in #336.

I would send a PR myself, but, for some reason, after regenerating the code I am getting a diff with size of a half of the project :smiling_face_with_tear:  And the changes are mostly unrelated.

Anyway, changing `String` to `json::Value` and regenerating the code should be sufficient.

### PR DESCRIPTION
**Pull request by xDarksome**
Resolves #403 #336

This PR:
- changes `any` JSON Schema type mapping to `json::Value`
- regenerates `fcm1` crate

### CODE REVIEW

**Comment by Byron** [comment]
Thanks a lot! It looks like a change that can be very useful, and thus far it seems to work. Please note that I removed the regenerated code from the commit - PRs are much easier to review and handle that way.

Once I have run it against all existing APIs without failure, this will be merged. Would you like a new release of the `fcm1` crate once that happens?

**Comment by Byron** [comment]
Closing as the commit was merged, after squashing it so GitHub can't detect this.

**Comment by xDarksome** [comment]
@Byron 

> Once I have run it against all existing APIs without failure, this will be merged. Would you like a new release of the fcm1 crate once that happens?

Yes, that would be great, thanks!

**Comment by Byron** [comment]
Alright, [here is new release](https://crates.io/crates/google-fcm1/5.0.2-beta-1+20220228).

**Pull request closed without merging**
