### PR TITLE
Revert "Merge branch 'format_types'"

### PR DESCRIPTION
**Pull request by andrewbaxter**
This reverts commit ed5dab2dbd1aa8d126b1253e8020bcf964f0ee34, reversing changes made to 93c8601fdca62f92f164957d9e86220f4f1b10f7.

There are some manual changes to include reverts of subsequent mrs, plus some manual fixups.  It builds, but I don't know if it's correct yet.

Related to discussion in https://github.com/Byron/google-apis-rs/pull/446

### CODE REVIEW

**Comment by andrewbaxter** [comment]
Okay AFAICT this works (no compile errors for storage or kms at least).  I'm not sure if I should regenerate everything in this MR or as a separate MR afterwards or what.

**Comment by Byron** [comment]
Thanks a lot for going through with it!

I think [this tests expectation](https://github.com/Byron/google-apis-rs/actions/runs/7410663915/job/20163470005?pr=463#step:4:504) could be fixed, the failure appears genuine. Could you do that?

Thanks again for giving it another shot.

> I'm not sure if I should regenerate everything in this MR or as a separate MR afterwards or what.

Please do not regenerate anything, such contributions are impossible to review. I regenerate myself before making a release.

**Comment by andrewbaxter** [comment]
Sorry, I'll have to look at that failure tomorrow.

**Comment by Byron** [comment]
No worries, this failure is expected, some python breakage that just happens without any change.

I think this PR will be merged soon.

**Comment by Byron** [comment]
After having caught up, and given your experience by now with the codebase, I think you could try to keep what is there locally, change the encoding to `base64` and that should solve all problems, right?

If not, we can still merge this PR and probably leave the encoding/decoding to the user.

I will wait until I hear from you.

**Comment by andrewbaxter** [comment]
Closed in favor of https://github.com/Byron/google-apis-rs/pull/446

**Pull request closed without merging**
