### PR TITLE
Update to yup-oauth 5.0, newest hyper, rustls etc. 

### PR DESCRIPTION
**Pull request by djrodgerspryor**
Here's a new PR with the generated files removed

### CODE REVIEW

**Comment by Byron** [comment]
Awesome, thanks so much! Just as a quick 'ping' I wanted to let you know that I will get to checking the PR and merging it 'soonish', there is a little too much going on here right now 😅.

**Comment by Byron** [comment]
Thanks a million! Believe it or not, I did try to remove them myself and update this PR with a fixed history but for some reason, I failed. It's strange because I thought I knew how git worked 😅.

Anyway, now that this is done let me restate I really want to get to take a look and get this off my desk and the google APIs back into a more operational state. Thanks for bearing with me on this!

[Here is my set of priorities right now](https://github.com/users/Byron/projects/1) even though I am happy to push this one up thinking it can probably be done in an hour or so.

**Comment by Byron** [comment]
I checked out the PR and tried to `cargo check` the youtube3 API and got this result:

```
    Checking google-youtube3 v1.0.14+20200709 (/Users/byron/dev/github.com/Byron/google-apis-rs/gen/youtube3)
error[E0599]: no method named `api_key` found for struct `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>` in the current scope
     --> src/api.rs:29675:50
      |
29675 |         let mut key = self.hub.auth.borrow_mut().api_key();
      |                                                  ^^^^^^^ method not found in `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>`
      |
      = help: items from traits can only be used if the trait is implemented and in scope
note: `Delegate` defines an item `api_key`, perhaps you need to implement it
     --> src/client.rs:110:1
      |
110   | pub trait Delegate {
      | ^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `api_key` found for struct `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>` in the current scope
     --> src/api.rs:29913:50
      |
29913 |         let mut key = self.hub.auth.borrow_mut().api_key();
      |                                                  ^^^^^^^ method not found in `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>`
      |
      = help: items from traits can only be used if the trait is implemented and in scope
note: `Delegate` defines an item `api_key`, perhaps you need to implement it
     --> src/client.rs:110:1
      |
110   | pub trait Delegate {
      | ^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `api_key` found for struct `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>` in the current scope
     --> src/api.rs:30171:50
      |
30171 |         let mut key = self.hub.auth.borrow_mut().api_key();
      |                                                  ^^^^^^^ method not found in `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>`
      |
      = help: items from traits can only be used if the trait is implemented and in scope
note: `Delegate` defines an item `api_key`, perhaps you need to implement it
     --> src/client.rs:110:1
      |
110   | pub trait Delegate {
      | ^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `api_key` found for struct `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>` in the current scope
     --> src/api.rs:30417:50
      |
30417 |         let mut key = self.hub.auth.borrow_mut().api_key();
      |                                                  ^^^^^^^ method not found in `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>`
      |
      = help: items from traits can only be used if the trait is implemented and in scope
note: `Delegate` defines an item `api_key`, perhaps you need to implement it
     --> src/client.rs:110:1
      |
110   | pub trait Delegate {
      | ^^^^^^^^^^^^^^^^^^

error[E0277]: the trait bound `HeaderValue: From<Mime>` is not satisfied
     --> src/api.rs:30712:41
      |
30712 | ...                   req_builder.header(CONTENT_TYPE, reader_mime_type.clone())
      |                                   ^^^^^^ the trait `From<Mime>` is not implemented for `HeaderValue`
      |
      = help: the following implementations were found:
                <HeaderValue as From<&'a HeaderValue>>
                <HeaderValue as From<HeaderName>>
                <HeaderValue as From<i16>>
                <HeaderValue as From<i32>>
              and 6 others
      = note: required because of the requirements on the impl of `Into<HeaderValue>` for `Mime`
      = note: required because of the requirements on the impl of `TryFrom<Mime>` for `HeaderValue`

error[E0308]: `if` and `else` have incompatible types
     --> src/api.rs:30716:29
      |
30706 |                            let request = if protocol == "simple" {
      |   _______________________________________-
30707 |  |                             let size = reader.seek(io::SeekFrom::End(0)).unwrap();
30708 |  |                 reader.seek(io::SeekFrom::Start(0)).unwrap();
30709 |  |                 if size > 2097152 {
...      |
30712 | /|                             req_builder.header(CONTENT_TYPE, reader_mime_type.clone())
30713 | ||                                      .header(CONTENT_LENGTH, size)
30714 | ||                                      .body(&mut reader);
      | ||________________________________________________________- expected because of this
30715 |  |                         } else {
30716 |  |                             req_builder.body(hyper::body::Body::empty())
      |  |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `()`, found enum `std::result::Result`
30717 |  |                         };
      |  |_________________________- `if` and `else` have incompatible types
      |
      = note: expected type `()`
                 found enum `std::result::Result<Request<Body>, hyper::http::Error>`

error[E0599]: no method named `api_key` found for struct `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>` in the current scope
     --> src/api.rs:34597:50
      |
34597 |         let mut key = self.hub.auth.borrow_mut().api_key();
      |                                                  ^^^^^^^ method not found in `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>`
      |
      = help: items from traits can only be used if the trait is implemented and in scope
note: `Delegate` defines an item `api_key`, perhaps you need to implement it
     --> src/client.rs:110:1
      |
110   | pub trait Delegate {
      | ^^^^^^^^^^^^^^^^^^

error: aborting due to 7 previous errors

Some errors have detailed explanations: E0277, E0308, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `google-youtube3`

To learn more, run the command again with --verbose.
make: *** [youtube3-cargo] Error 101
➜  google-apis-rs git:(upgrade_no_regen) ✗ tig
➜  google-apis-rs git:(upgrade_no_regen) ✗ make youtube3-cargo ARGS=check
```

When trying the same with `make youtube3-cli-cargo ARGS=check` cargo couldn't get started due to a duplicate key in the manifest. Surely easy to fix, but secondary.

Have you encountered similar issues? A good way to test if everything builds is to run `make cargo-api ARGS=check` to `cargo check` every API it knows. All are expected to check correctly. This should be repeated with `ARGS=doc`. From there, the same can be done for CLIs using `make cargo-cli ARGS=check` to make sure they still fit together.

I am happy to take a look as well from time to time, trying to reduce the amount of issues one by one, but I would be happy to hear about your process and how you verified it works. Maybe a bug creeped in when removing the generated files?

Thanks for your help!

**Comment by dvaerum** [comment]
Hey @djrodgerspryor
CC: @Byron 

I found the problem, in the `doit()` method for `FileGetCall`.

In line following line you assume that the only type of data there can be returned is UTF8 string, but if one is downloading a binary this is no longer, true.
https://github.com/djrodgerspryor/google-apis-rs/blob/89fe087c825802b65785a8b37beb83d1539171f3/gen/drive3/src/api.rs#L9972-L9982
What I don't understand is what you are trying to do with this `reconstructed_result` variable in 9981. To me, it looks like you are re-building the `Response` object/struct, but I cannot figure out why, can you help me understand?
*Note:* I have been playing around with it and I simply cannot find the need for rebuilding the `Response` object/struct, but maybe it is need somewhere.

*Ref to the entire method:*
https://github.com/djrodgerspryor/google-apis-rs/blob/89fe087c825802b65785a8b37beb83d1539171f3/gen/drive3/src/api.rs#L9849-L10017

**Comment by dvaerum** [comment]
> I checked out the PR and tried to `cargo check` the youtube3 API and got this result:
> 
> ```
>     Checking google-youtube3 v1.0.14+20200709 (/Users/byron/dev/github.com/Byron/google-apis-rs/gen/youtube3)
> error[E0599]: no method named `api_key` found for struct `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>` in the current scope
>      --> src/api.rs:29675:50
>       |
> 29675 |         let mut key = self.hub.auth.borrow_mut().api_key();
>       |                                                  ^^^^^^^ method not found in `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>`
>       |
>       = help: items from traits can only be used if the trait is implemented and in scope
> note: `Delegate` defines an item `api_key`, perhaps you need to implement it
>      --> src/client.rs:110:1
>       |
> 110   | pub trait Delegate {
>       | ^^^^^^^^^^^^^^^^^^
> 
> error[E0599]: no method named `api_key` found for struct `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>` in the current scope
>      --> src/api.rs:29913:50
>       |
> 29913 |         let mut key = self.hub.auth.borrow_mut().api_key();
>       |                                                  ^^^^^^^ method not found in `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>`
>       |
>       = help: items from traits can only be used if the trait is implemented and in scope
> note: `Delegate` defines an item `api_key`, perhaps you need to implement it
>      --> src/client.rs:110:1
>       |
> 110   | pub trait Delegate {
>       | ^^^^^^^^^^^^^^^^^^
> 
> error[E0599]: no method named `api_key` found for struct `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>` in the current scope
>      --> src/api.rs:30171:50
>       |
> 30171 |         let mut key = self.hub.auth.borrow_mut().api_key();
>       |                                                  ^^^^^^^ method not found in `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>`
>       |
>       = help: items from traits can only be used if the trait is implemented and in scope
> note: `Delegate` defines an item `api_key`, perhaps you need to implement it
>      --> src/client.rs:110:1
>       |
> 110   | pub trait Delegate {
>       | ^^^^^^^^^^^^^^^^^^
> 
> error[E0599]: no method named `api_key` found for struct `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>` in the current scope
>      --> src/api.rs:30417:50
>       |
> 30417 |         let mut key = self.hub.auth.borrow_mut().api_key();
>       |                                                  ^^^^^^^ method not found in `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>`
>       |
>       = help: items from traits can only be used if the trait is implemented and in scope
> note: `Delegate` defines an item `api_key`, perhaps you need to implement it
>      --> src/client.rs:110:1
>       |
> 110   | pub trait Delegate {
>       | ^^^^^^^^^^^^^^^^^^
> 
> error[E0277]: the trait bound `HeaderValue: From<Mime>` is not satisfied
>      --> src/api.rs:30712:41
>       |
> 30712 | ...                   req_builder.header(CONTENT_TYPE, reader_mime_type.clone())
>       |                                   ^^^^^^ the trait `From<Mime>` is not implemented for `HeaderValue`
>       |
>       = help: the following implementations were found:
>                 <HeaderValue as From<&'a HeaderValue>>
>                 <HeaderValue as From<HeaderName>>
>                 <HeaderValue as From<i16>>
>                 <HeaderValue as From<i32>>
>               and 6 others
>       = note: required because of the requirements on the impl of `Into<HeaderValue>` for `Mime`
>       = note: required because of the requirements on the impl of `TryFrom<Mime>` for `HeaderValue`
> 
> error[E0308]: `if` and `else` have incompatible types
>      --> src/api.rs:30716:29
>       |
> 30706 |                            let request = if protocol == "simple" {
>       |   _______________________________________-
> 30707 |  |                             let size = reader.seek(io::SeekFrom::End(0)).unwrap();
> 30708 |  |                 reader.seek(io::SeekFrom::Start(0)).unwrap();
> 30709 |  |                 if size > 2097152 {
> ...      |
> 30712 | /|                             req_builder.header(CONTENT_TYPE, reader_mime_type.clone())
> 30713 | ||                                      .header(CONTENT_LENGTH, size)
> 30714 | ||                                      .body(&mut reader);
>       | ||________________________________________________________- expected because of this
> 30715 |  |                         } else {
> 30716 |  |                             req_builder.body(hyper::body::Body::empty())
>       |  |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `()`, found enum `std::result::Result`
> 30717 |  |                         };
>       |  |_________________________- `if` and `else` have incompatible types
>       |
>       = note: expected type `()`
>                  found enum `std::result::Result<Request<Body>, hyper::http::Error>`
> 
> error[E0599]: no method named `api_key` found for struct `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>` in the current scope
>      --> src/api.rs:34597:50
>       |
> 34597 |         let mut key = self.hub.auth.borrow_mut().api_key();
>       |                                                  ^^^^^^^ method not found in `RefMut<'_, Authenticator<HttpsConnector<HttpConnector>>>`
>       |
>       = help: items from traits can only be used if the trait is implemented and in scope
> note: `Delegate` defines an item `api_key`, perhaps you need to implement it
>      --> src/client.rs:110:1
>       |
> 110   | pub trait Delegate {
>       | ^^^^^^^^^^^^^^^^^^
> 
> error: aborting due to 7 previous errors
> 
> Some errors have detailed explanations: E0277, E0308, E0599.
> For more information about an error, try `rustc --explain E0277`.
> error: could not compile `google-youtube3`
> 
> To learn more, run the command again with --verbose.
> make: *** [youtube3-cargo] Error 101
> ➜  google-apis-rs git:(upgrade_no_regen) ✗ tig
> ➜  google-apis-rs git:(upgrade_no_regen) ✗ make youtube3-cargo ARGS=check
> ```
> 
> When trying the same with `make youtube3-cli-cargo ARGS=check` cargo couldn't get started due to a duplicate key in the manifest. Surely easy to fix, but secondary.
> 
> Have you encountered similar issues? A good way to test if everything builds is to run `make cargo-api ARGS=check` to `cargo check` every API it knows. All are expected to check correctly. This should be repeated with `ARGS=doc`. From there, the same can be done for CLIs using `make cargo-cli ARGS=check` to make sure they still fit together.
> 
> I am happy to take a look as well from time to time, trying to reduce the amount of issues one by one, but I would be happy to hear about your process and how you verified it works. Maybe a bug creeped in when removing the generated files?
> 
> Thanks for your help!

@Byron I have been looking at the problem with the `api_key()` call, and it turns out that `yup_oauth2` removed the method then they moved from version [v2.0.4 (see link)](https://docs.rs/yup-oauth2/2.0.4/src/yup_oauth2/authenticator.rs.html#326-331) to [v3+ (see link)](https://docs.rs/yup-oauth2/3.0.4/src/yup_oauth2/authenticator.rs.html).
Now what the method `api_key()` did was to return the `client_id` value from [the struct `` (see link)](https://docs.rs/yup-oauth2/5.1.0/src/yup_oauth2/types.rs.html#118-138) which is still around.
If the `api_key`/`client_id` is needed, I guess we need to find a new way to obtain it :sweat_smile:, but I have not been able to find a way to do that.

```rust
        let mut key = self.hub.auth.borrow_mut().api_key();
        if key.is_none() {
            key = dlg.api_key();
        }
        match key {
            Some(value) => params.push(("key", value)),
            None => {
                dlg.finished(false);
                return Err(client::Error::MissingAPIKey)
            }
        }
```

**Comment by Byron** [comment]
Thanks for investigating! It looks like nobody implements `GetToken` in a way that would return anything else but `None`, so for now I removed that call entirely. In v5 [this is actually implemented, but if @dermesser is unsure about how it's implemented, I am not sure how this can be useful in practice.

I am now compiling all APIs to see if there is anything else left to do there. If not, CLI and docs are next. CLI will probably need quite some adjustment to handle async, but now that we got this far that won't stop us :D.

**Comment by Byron** [comment]
Ok, libs compile once again! @dvaerum, maybe you could do me the favour and check if some of the blacklisted APIs now actually build. Some didn't because a type clashed, but now that shouldn't be possible anymore as API types have their own namespace.

Later I will take a look at the CLIs (but of course you are welcome to take a look there as well).
My plan is to merge this once everything compiles properly, update JSON files, and republish all crates under a new major release.

**Comment by Byron** [comment]
CLIs and doc tests build now 💪

**Comment by Byron** [comment]
Docs seem to work as well now, but I am building everything to see if that's truly correct.

**Comment by Byron** [comment]
So it's done, I think, and I will leave my computer publishing version 2 of all existing and some new google crates, now with async support.

@dvaerum
> What I don't understand is what you are trying to do with this reconstructed_result variable in line 9981. To me, it looks like you are re-building the Response object/struct, but I cannot figure out why, can you help me understand?
Note: I have been playing around with it and I simply cannot find the need for rebuilding the Response object/struct, but maybe it is needed somewhere

While doing my fixes I saw that too (among other blunders) and agree that this is not the way to do it. Not only does it download everything into memory, but it will also require UTF-8 encoding.

Let's have another issue (or PR) to get a fix for that next.

**Comment by djrodgerspryor** [comment]
Thanks!

**Pull request merged**
