### PR TITLE
Expose features from yup-oauth2

### PR DESCRIPTION
**Pull request by tylerhawkes**
Fixes https://github.com/Byron/google-apis-rs/issues/236

I didn't include everything that changed in gen as I'm still running tests and there are a lot of mako errors on my machine. I can include them if needed.

### CODE REVIEW

**Comment by Byron** [comment]
Thank a lot! The fix is much appreciated! If you need any particular API to be published with it, please let me know.

**Comment by tylerhawkes** [comment]
I'm just using google-storage1 at the moment. If you could push it that would be awesome!

**Comment by Byron** [comment]
Perfect! `google-storage1 v1.0.11+20190624` was just published with the changes provided in this PR.
Please let me know when you need other crates, too.

**Comment by ErichDonGubler** [comment]
I use `google-gmail1` and fairly frequently run into this issue. I'm hoping to use `google-cloudiot1` soon, so I felt it'd be worth piping up. You should consider pushing the other crates with changes soon -- I'm sure there are several people waiting for these changes to propagate to the other crates!

Funnily enough, I work at the same place @tylerhawkes does, just not on the same team. :)

**Comment by Byron** [comment]
@ErichDonGubler Thanks for letting me know. I will see to get to it soon’ish.

**Comment by Byron** [comment]
@ErichDonGubler All crates have been republished with the latest version from master.

**Pull request merged**
