### PR TITLE
Fix Travis Yaml file

### PR DESCRIPTION
**Pull request by TheBiggerGuy**
The Travis Yaml file was invalid after #205

### CODE REVIEW

**Comment by TheBiggerGuy** [comment]
Rust stable had a runtime of 6m 33 seconds. https://travis-ci.org/Byron/google-apis-rs/jobs/444372166
I am going to restart it a check the cache works, flush the cache and repeat, make sure it is working.

**Comment by TheBiggerGuy** [comment]
Cached build took 3m 5 seconds so 2x speed improvement. Unfortunately the Python (pip/wheel) cache does not work due to the virtualenv config.

**Comment by Byron** [comment]
Pretty neat already! Can't wait for it to land in master :).

**Comment by TheBiggerGuy** [comment]
So without a working `.pyenv_cache` the OSX builds are ~3mins slower. To be clear this is a cache of the Python binary, this is due to an old version of Python on Travis, and not the Python VirtualEnv or Pip/Wheel cache.

**Pull request merged**
