### PR TITLE
feat(hub): Allow overriding rootUrl and baseUrl

### PR DESCRIPTION
**Pull request by LegNeato**
Allow the hub to override `rootUrl` and `baseUrl` for the service.
This is useful for pointing at localhost for testing or a proxy.

### CODE REVIEW

**Comment by LegNeato** [comment]
(test failures on nightly look unrelated)

**Comment by Byron** [comment]
Sorry for letting you hang for so long, your contribution is very much appreciated!
I will get to it next week I think.

**Comment by LegNeato** [comment]
No worries, take your time...I definitely do not consider 2 days over a weekend a long time 😃

**Comment by Byron** [comment]
@LegNeato Thanks for the contribution! A great idea to add this capability :)!
There is only one thing I improved, which is the usage of `std::mem::replace` instead of the usual swap code `t=x;x=y;t` - the former avoid borrow checker issues.

**Pull request merged**
