### PR TITLE
Switch to async io

### PR DESCRIPTION
**Pull request by MOZGIII**
Mako doesn't work, instructions unclear, send help. Also, 5 am here. Will resume this tomorrow..?

The basic approach is established, the rest shouldn't be too difficult.

### CODE REVIEW

**Comment by MOZGIII** [comment]
Turns out the vendored `virtualenv` has a bug that breaks venv on my system. I recommend updating.

**Comment by Byron** [comment]
Thanks for getting started in this, it would indeed be great if these blocking calls could go away!

> Turns out the vendored `virtualenv` has a bug that breaks venv on my system. I recommend updating.

Indeed, the `makefile` installs `virtualenv` in a particular version for the user, which I consider bad practice as well. Maybe you can fix this in another PR? I don't know how portable `virtualenv` is but I'd expect the worst, but it's probably better than unconditionally installing python packages on the callers system.

**Comment by MOZGIII** [comment]
I'm not sure I want to tackle this at this time. However, I'd suggest using nix (https://nixos.org/) for keeping the build environment up to date. It is portable, and can really be an opt-in, instead of being a mandatory part of the `Makefile`.
The benefit of nix is that it can really elegantly manage all the dependencies, including the python itself. The downside it it won't work on Windows.

**Comment by Byron** [comment]
I am sorry, but think it's best to close this PR due to inactivity. Please feel free to reopen or resubmit.

Thanks for your understanding.

**Pull request closed without merging**
